/**
 * 노션 스타일 단축키 기본 바인딩을 정의합니다.
 */

import type { ShortcutBinding } from "@features/shortcuts/model/shortcuts.types.ts";

/**
 * 기본 제공하는 노션 스타일 단축키 바인딩 목록입니다.
 */
export const NOTION_SHORTCUT_BINDINGS: ShortcutBinding[] = [
  {
    combo: "Mod+P",
    command: "open-search",
    scope: "global",
    label: "Open Search",
    description: "Search for pages or jump to a document.",
    allowInInput: true,
  },
  {
    combo: "Mod+K",
    command: "open-search",
    scope: "global",
    label: "Open Search",
    description: "Search for pages or jump to a document.",
    allowInInput: true,
  },
  {
    combo: "Mod+N",
    command: "new-page",
    scope: "global",
    label: "New Page",
    description: "Create a new page.",
    allowInInput: true,
  },
  {
    combo: "Mod+S",
    command: "save-page",
    scope: "global",
    label: "Save Page",
    description: "Save the current page.",
    allowInInput: true,
  },
  {
    combo: "Mod+Z",
    command: "undo-edit",
    scope: "text",
    label: "Undo",
    description: "Undo the latest local edit.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+Z",
    command: "redo-edit",
    scope: "text",
    label: "Redo",
    description: "Redo the latest undone local edit.",
    allowInInput: true,
  },
  {
    combo: "Mod+Y",
    command: "redo-edit",
    scope: "text",
    label: "Redo",
    description: "Redo the latest undone local edit.",
    allowInInput: true,
  },
  {
    combo: "Mod+/",
    command: "show-shortcuts",
    scope: "global",
    label: "Show Shortcuts",
    description: "Open the keyboard shortcuts help.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+L",
    command: "toggle-theme",
    scope: "global",
    label: "Toggle Theme",
    description: "Toggle between light and dark theme.",
    allowInInput: true,
  },
  {
    combo: "Escape",
    command: "close-overlay",
    scope: "global",
    label: "Close Overlay",
    description: "Close an open menu, dialog, or selection.",
    allowInInput: true,
  },
  {
    combo: "Mod+A",
    command: "select-current-block",
    scope: "text",
    label: "Select Current Block",
    description: "Select the block containing the cursor.",
    allowInInput: true,
  },
  {
    combo: "Escape",
    command: "clear-block-selection",
    scope: "text",
    label: "Clear Block Selection",
    description: "Leave text editing and select or clear blocks.",
    allowInInput: true,
  },
  {
    combo: "Enter",
    command: "edit-selected-block",
    scope: "text",
    label: "Edit Selected Block",
    description: "Edit the currently selected block.",
    allowInInput: false,
  },
  {
    combo: "Mod+/",
    command: "open-block-menu",
    scope: "text",
    label: "Open Block Menu",
    description: "Open the block action menu for selected blocks.",
    allowInInput: true,
  },
  {
    combo: "Mod+D",
    command: "duplicate-block",
    scope: "text",
    label: "Duplicate Block",
    description: "Duplicate the selected block.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+ArrowUp",
    command: "move-block-up",
    scope: "text",
    label: "Move Block Up",
    description: "Move the selected block upward.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+ArrowDown",
    command: "move-block-down",
    scope: "text",
    label: "Move Block Down",
    description: "Move the selected block downward.",
    allowInInput: true,
  },
  {
    combo: "Tab",
    command: "indent-block",
    scope: "text",
    label: "Indent Block",
    description: "Indent the current block deeper.",
    allowInInput: true,
  },
  {
    combo: "Shift+Tab",
    command: "outdent-block",
    scope: "text",
    label: "Outdent Block",
    description: "Move the current block outward.",
    allowInInput: true,
  },
  {
    combo: "Mod+Enter",
    command: "modify-current-block",
    scope: "text",
    label: "Modify Current Block",
    description: "Open, toggle, or modify the current block.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+0",
    command: "turn-into-text",
    scope: "text",
    label: "Turn Into Text",
    description: "Convert the current line into plain text.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+0",
    command: "turn-into-text",
    scope: "text",
    label: "Turn Into Text",
    description: "Convert the current line into plain text.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+1",
    command: "turn-into-heading-1",
    scope: "text",
    label: "Heading 1",
    description: "Convert the current block to heading 1.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+1",
    command: "turn-into-heading-1",
    scope: "text",
    label: "Heading 1",
    description: "Convert the current block to heading 1.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+2",
    command: "turn-into-heading-2",
    scope: "text",
    label: "Heading 2",
    description: "Convert the current block to heading 2.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+2",
    command: "turn-into-heading-2",
    scope: "text",
    label: "Heading 2",
    description: "Convert the current block to heading 2.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+3",
    command: "turn-into-heading-3",
    scope: "text",
    label: "Heading 3",
    description: "Convert the current block to heading 3.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+3",
    command: "turn-into-heading-3",
    scope: "text",
    label: "Heading 3",
    description: "Convert the current block to heading 3.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+4",
    command: "turn-into-to-do",
    scope: "text",
    label: "To-do List",
    description: "Convert the current block to a to-do item.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+4",
    command: "turn-into-to-do",
    scope: "text",
    label: "To-do List",
    description: "Convert the current block to a to-do item.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+5",
    command: "turn-into-bulleted-list",
    scope: "text",
    label: "Bulleted List",
    description: "Convert the current block to a bulleted list.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+5",
    command: "turn-into-bulleted-list",
    scope: "text",
    label: "Bulleted List",
    description: "Convert the current block to a bulleted list.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+6",
    command: "turn-into-numbered-list",
    scope: "text",
    label: "Numbered List",
    description: "Convert the current block to a numbered list.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+6",
    command: "turn-into-numbered-list",
    scope: "text",
    label: "Numbered List",
    description: "Convert the current block to a numbered list.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+7",
    command: "turn-into-toggle-list",
    scope: "text",
    label: "Toggle List",
    description: "Convert the current block to a toggle list.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+7",
    command: "turn-into-toggle-list",
    scope: "text",
    label: "Toggle List",
    description: "Convert the current block to a toggle list.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+8",
    command: "turn-into-code-block",
    scope: "text",
    label: "Code Block",
    description: "Convert the current block to a code block.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+8",
    command: "turn-into-code-block",
    scope: "text",
    label: "Code Block",
    description: "Convert the current block to a code block.",
    allowInInput: true,
  },
  {
    combo: "Mod+Alt+9",
    command: "turn-into-page",
    scope: "text",
    label: "Turn Into Page",
    description: "Turn the current block into a page.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+9",
    command: "turn-into-page",
    scope: "text",
    label: "Turn Into Page",
    description: "Turn the current block into a page.",
    allowInInput: true,
  },
  {
    combo: "Mod+B",
    command: "format-bold",
    scope: "text",
    label: "Bold",
    description: "Apply bold formatting.",
    allowInInput: true,
  },
  {
    combo: "Mod+I",
    command: "format-italic",
    scope: "text",
    label: "Italic",
    description: "Apply italic formatting.",
    allowInInput: true,
  },
  {
    combo: "Mod+U",
    command: "format-underline",
    scope: "text",
    label: "Underline",
    description: "Apply underline formatting.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+S",
    command: "format-strikethrough",
    scope: "text",
    label: "Strikethrough",
    description: "Apply strikethrough formatting.",
    allowInInput: true,
  },
  {
    combo: "Mod+E",
    command: "format-inline-code",
    scope: "text",
    label: "Inline Code",
    description: "Apply inline code formatting.",
    allowInInput: true,
  },
  {
    combo: "Mod+K",
    command: "create-link",
    scope: "text",
    label: "Create Link",
    description: "Turn the selection into a link.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+M",
    command: "comment-selection",
    scope: "text",
    label: "Comment",
    description: "Add a comment to the current selection.",
    allowInInput: true,
  },
  {
    combo: "Mod+Shift+H",
    command: "apply-last-color",
    scope: "text",
    label: "Apply Last Color",
    description: "Apply the last text or highlight color used.",
    allowInInput: true,
  },
];
